### ISSUE TITLE
Loop with setup.sh and runme.sh

### ISSUE THREAD

**Issue by WiZaR5789** [bsharper/sbremote#1]
Hi, could you help me with your program i got into a loop running setup.sh everything is fine however after running runme.sh i get a request to run setup.sh again. All dependencies from requirements installed. Python version as well as the problem visible on the screen.
![image](https://user-images.githubusercontent.com/36671802/201497235-85785d54-8236-41f8-bdbc-52c1c7c156d1.png)
Debian 11

**Comment by DebugDax** [comment]
I had to go into setup.sh, runme.sh, and restart.sh and change all the python calls to python3.
Even though it does a check for python vs python3 command, it doesn't actually use python3 when calling other scripts.

In all 3 there's one at the bottom.

**Comment by bsharper** [comment]
Can you provide some info on your setup? Is this a Linux host?

**Comment by bsharper** [comment]
Closing, let me know if this is still an issue.
