### ISSUE TITLE
How to suppress "Move on Sponsor" Announcement ?

### ISSUE THREAD

**Issue by Tech33** [bsharper/sbremote#2]
Firstly, Great work...its working great on my MAC M1....is there any way to suppress "Move on Sponsor" Announcement  quite annoying tbh..

**Comment by bsharper** [comment]
Oh haha... sorry about that. It initially said something much worse that starts with "f" and rhymes with duck, but I changed it to at the last minute to something less vulgar. It shouldn't be enabled other than in debug mode, but I may have committed code with it still enabled.

To fix this, edit the file `sb_remote.py`. Near the top you should see `announce_skips = True`. Change that to `announce_skips = False` and restart the program. It should stop talking to you after that.
